### ISSUE TITLE
我在使用滑块识别的功能的时候报错

### ISSUE THREAD

**Issue by 1756816846** [86maid/ddddocr#1]
thread 'actix-rt|system:0|arbiter:0' panicked at 'image width must be greater than or equal to template width', C:\Users\XChuang233\.cargo\registry\src\index.crates.io-6f17d22bba15001f\imageproc-0.23.0\src\template_matching.rs:46:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
我在python版本运行就可以，如果把两个图片的参数换一下，能运行，但是结果不对
![image](https://github.com/86maid/ddddocr/assets/22480057/a9031229-b358-4c8e-9f7a-20c7d589a9dd)
![image](https://github.com/86maid/ddddocr/assets/22480057/cd4ef514-a835-4ebb-9b21-6180a73acb54)

**Comment by 86maid** [comment]
收到，我看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午2:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




 
thread 'actix-rt|system:0|arbiter:0' panicked at 'image width must be greater than or equal to template width', C:\Users\XChuang233.cargo\registry\src\index.crates.io-6f17d22bba15001f\imageproc-0.23.0\src\template_matching.rs:46:5
 note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
 我在python版本运行就可以，如果把两个图片的参数换一下，能运行，但是结果不对

**Comment by 1756816846** [comment]
![img_quekou_ok](https://github.com/86maid/ddddocr/assets/22480057/c0070a90-e2b3-425f-b98d-eadcd78fc629)
![img_back](https://github.com/86maid/ddddocr/assets/22480057/3a10894c-1143-42dd-9fb8-4b68355d27d3)
给你图片，你测试一下，我在python版本也是用这俩测试的

**Comment by 86maid** [comment]
好的，谢谢












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午2:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




 

 
 给你图片，你测试一下，我在python版本也是用这俩测试的

**Comment by 1756816846** [comment]
我在python版本使用的代码是
`
def get_gap(target_img:bytes, background_img:bytes):
    det = ddddocr.DdddOcr(det=False, ocr=False, show_ad=False)
    res = det.slide_match(target_img, background_img,simple_target=True)
    return res["target"]

`

**Comment by 1756816846** [comment]
> simple_target选项不为True的时候就会报错，要是能加这个选项就好了

**Comment by 86maid** [comment]
好












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




  
simple_target选项不为True的时候就会报错，要是能加这个选项就好了

**Comment by 86maid** [comment]
你是说，Python版本也报错对么？












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




  
simple_target选项不为True的时候就会报错，要是能加这个选项就好了

**Comment by 1756816846** [comment]
> 你是说，Python版本也报错对么？ xchuang233 ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月11日(周五) 下午2:49 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) simple_target选项不为True的时候就会报错，要是能加这个选项就好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是的，不是因为你的代码问题，是没开那个选项

**Comment by 86maid** [comment]
你希望返回错误，而不是崩溃？












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午3:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




  
你是说，Python版本也报错对么？ xchuang233 @.***
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年8月11日(周五) 下午2:49 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) simple_target选项不为True的时候就会报错，要是能加这个选项就好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
是的，不是因为你的代码问题，是没开那个选项

**Comment by 1756816846** [comment]
能不能优化为post参数




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)





 你希望返回错误，而不是崩溃？ 
 
 
 
 
 
 
 
 
 
 
 
 
 xchuang233 
 ***@***.*** 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年8月11日(周五) 下午3:02 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) 
 
 
 
 
    
 你是说，Python版本也报错对么？ xchuang233 @.*** 
  … 
  ---原始邮件--- 发件人: @.&amp;gt; 发送时间: 2023年8月11日(周五) 下午2:49 收件人: @.&amp;gt;; 抄送: @.@.&amp;gt;; 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) simple_target选项不为True的时候就会报错，要是能加这个选项就好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&amp;gt; 
    
 是的，不是因为你的代码问题，是没开那个选项

**Comment by 86maid** [comment]
我知道了












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




 能不能优化为post参数 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年8月11日(星期五) 下午3:03 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) 
 
 
 
 
 
  你希望返回错误，而不是崩溃？  
   
   
   
   
   
   
   
   
   
   
   
   
  xchuang233  
  ***@***.***  
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年8月11日(周五) 下午3:02  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)  
   
   
   
   
      
  你是说，Python版本也报错对么？ xchuang233 @.***  
   …  
   ---原始邮件--- 发件人: @.&amp;amp;gt; 发送时间: 2023年8月11日(周五) 下午2:49 收件人: @.&amp;amp;gt;; 抄送: @.@.&amp;amp;gt;; 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) simple_target选项不为True的时候就会报错，要是能加这个选项就好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&amp;amp;gt;  
      
  是的，不是因为你的代码问题，是没开那个选项

**Comment by 86maid** [comment]
我刚才测试了一下Python版本，不管是不是simple，识别结果都是错的












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




 能不能优化为post参数 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年8月11日(星期五) 下午3:03 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) 
 
 
 
 
 
  你希望返回错误，而不是崩溃？  
   
   
   
   
   
   
   
   
   
   
   
   
  xchuang233  
  ***@***.***  
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年8月11日(周五) 下午3:02  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)  
   
   
   
   
      
  你是说，Python版本也报错对么？ xchuang233 @.***  
   …  
   ---原始邮件--- 发件人: @.&amp;amp;gt; 发送时间: 2023年8月11日(周五) 下午2:49 收件人: @.&amp;amp;gt;; 抄送: @.@.&amp;amp;gt;; 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) simple_target选项不为True的时候就会报错，要是能加这个选项就好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&amp;amp;gt;  
      
  是的，不是因为你的代码问题，是没开那个选项

**Comment by 86maid** [comment]
噗哈哈，我刚刚发现你给我的图片，形状不一样。。。我知道你要做啥了












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)




 能不能优化为post参数 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年8月11日(星期五) 下午3:03 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) 
 
 
 
 
 
  你希望返回错误，而不是崩溃？  
   
   
   
   
   
   
   
   
   
   
   
   
  xchuang233  
  ***@***.***  
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2023年8月11日(周五) 下午3:02  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1)  
   
   
   
   
      
  你是说，Python版本也报错对么？ xchuang233 @.***  
   …  
   ---原始邮件--- 发件人: @.&amp;amp;gt; 发送时间: 2023年8月11日(周五) 下午2:49 收件人: @.&amp;amp;gt;; 抄送: @.@.&amp;amp;gt;; 主题: Re: [86maid/ddddocr] 我在使用滑块识别的功能的时候报错 (Issue #1) simple_target选项不为True的时候就会报错，要是能加这个选项就好了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&amp;amp;gt;  
      
  是的，不是因为你的代码问题，是没开那个选项
